/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Vehiculo;

/**
 *
 * @author 1234
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_registrar_vehiculos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTipoVehiculo = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jPanel_Retirar_vehiculos = new javax.swing.JPanel();
        jPanel_Administrar_vehiculos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 0));

        jPanel_registrar_vehiculos.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_registrar_vehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registro de ingreso de vehiculos al parqueadero");
        jPanel_registrar_vehiculos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtTipoVehiculo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtTipoVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        txtTipoVehiculo.setIcon(new javax.swing.ImageIcon("C:\\Users\\1234\\Downloads\\coche-alternativo.png")); // NOI18N
        txtTipoVehiculo.setText("TIPO DE VEHICULO:");
        jPanel_registrar_vehiculos.add(txtTipoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 190, 40));

        txtPlaca.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(0, 0, 0));
        txtPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p-cuadrado.png"))); // NOI18N
        txtPlaca.setText("PLACA:");
        jPanel_registrar_vehiculos.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 30));

        txtPropietario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtPropietario.setForeground(new java.awt.Color(0, 0, 0));
        txtPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/usuario (1).png"))); // NOI18N
        txtPropietario.setText("PROPIETARIO:");
        jPanel_registrar_vehiculos.add(txtPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 150, 30));

        jTextField2.setBackground(new java.awt.Color(255, 255, 0));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel_registrar_vehiculos.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, 30));

        jTextField3.setBackground(new java.awt.Color(255, 255, 0));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel_registrar_vehiculos.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 150, 30));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 0));
        jComboBox1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "carro", "moto" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel_registrar_vehiculos.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 172, 150, 35));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 0));
        btnRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        jPanel_registrar_vehiculos.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jTabbedPane1.addTab("Registrar Vehiculo", jPanel_registrar_vehiculos);

        jPanel_Retirar_vehiculos.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_Retirar_vehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Retirar Vehiculos", jPanel_Retirar_vehiculos);

        jPanel_Administrar_vehiculos.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_Administrar_vehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Administrar Vehiculos ", jPanel_Administrar_vehiculos);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 480, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/EASY (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 500, 500));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SISTEMA DE PARQUEADERO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo (2) (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        CerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        CerrarSesion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cerrar-sesion (1).png"))); // NOI18N
        CerrarSesion.setText("CERRAR SESION");
        jPanel1.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         // 1. Validar que los campos no estén vacíos
    if (txtPlaca.getText().trim().isEmpty() || txtPropietario.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.");
        return; // Detiene la ejecución si falta algún dato
    }
    
    // 2. Si seleccionó el mensaje por defecto del combo (ej. "Seleccione:")
    if (txtTipoVehiculo.getText().toString().equalsIgnoreCase("Seleccione:")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un tipo de vehículo válido.");
        return;
    }

    // 3. Crear el objeto Vehiculo y asignarle los datos del formulario
      Vehiculo nuevoVehiculo = new Vehiculo();
    
    nuevoVehiculo.setPlaca(txtPlaca.getText().trim().toUpperCase()); // Guarda la placa en mayúsculas
    nuevoVehiculo.setPropietario(txtPropietario.getText().trim());
    nuevoVehiculo.setTipo_vehiculo(txtTipoVehiculo.getText().toString()); // Devolverá "carro" o "moto"
    
    // Como en tu Base de Datos pusiste que 'hora_entrada' sea DEFAULT CURRENT_TIMESTAMP,
    // puedes pasar este campo vacío o null y la base de datos le pondrá la hora actual solita.
    nuevoVehiculo.setHora_entrada(null); 
    nuevoVehiculo.setHora_salida(null); // Al ingresar, no tiene hora de salida
    nuevoVehiculo.setEstado("parqueado"); // Todo vehículo ingresa con estado "parqueado"
    nuevoVehiculo.setValor_pagado(0.0); // Al ingresar, todavía debe 0
    
    // 4. Instanciar el controlador y enviar el objeto a la base de datos
    controlador.VehiculoController controlVehiculo = new controlador.VehiculoController();
    
    if (controlVehiculo.guardar(nuevoVehiculo)) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Vehículo registrado con éxito!");
        
        // 5. Limpiar los campos para un nuevo registro
        txtPlaca.setText("");
        txtPropietario.setText("");
        txtTipoVehiculo.setText(""); // Regresa al "Seleccione:"
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el vehículo. Verifique si la placa ya existe.");
     }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Administrar_vehiculos;
    private javax.swing.JPanel jPanel_Retirar_vehiculos;
    private javax.swing.JPanel jPanel_registrar_vehiculos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JLabel txtPropietario;
    private javax.swing.JLabel txtTipoVehiculo;
    // End of variables declaration//GEN-END:variables
}
